# Generated by Django 4.2.1 on 2023-10-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('banner_img', models.ImageField(upload_to='banner')),
                ('view_type', models.CharField(choices=[('mobile', 'Mobile'), ('pc', 'PC')], default='pc', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('value', models.JSONField(default=list)),
            ],
        ),
    ]
