# Generated by Django 4.2.1 on 2023-05-31 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('logged_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(max_length=100)),
                ('session_value', models.CharField(max_length=100)),
            ],
        ),
    ]
