# Generated by Django 4.2.1 on 2023-08-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(unique=True)),
                ('item_name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('image', models.JSONField()),
                ('review', models.JSONField()),
                ('purchases_number', models.BigIntegerField()),
            ],
            options={
                'db_table': 'utazon_item',
            },
        ),
    ]
