# Generated by Django 4.2.1 on 2023-08-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.BigIntegerField()),
                ('item_name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('image', models.JSONField(blank=True, null=True)),
                ('review', models.JSONField(blank=True, null=True)),
                ('purchases_number', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'utazon_item',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sale_status', models.BooleanField(default=False)),
                ('discount_rate', models.IntegerField()),
                ('sale_start', models.DateTimeField()),
                ('sale_end', models.DateTimeField()),
                ('item_id', models.OneToOneField(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='config.item')),
            ],
            options={
                'db_table': 'utazon_sale',
            },
        ),
    ]
